Fetch feeds in parralel
pelican-plugins/webring pull request #15
Opened 2022-02-27 14:14 UTC by mlcdf

Fixes #9 with a backward compatible solution using the underated : `concurrent.futures.ThreadPoolExecutor`.

I'm not really sure how to add tests to test this. 

### To test this locally :
```
# change the value on the max_workers: 1, then 100
with concurrent.futures.ThreadPoolExecutor(max_workers=1) as executor:
```

 ```
 # add a test like this one
 def test_parrallel_fetch(self):
        self.set_feeds(["https://httpbin.org/delay/2" for _ in range(0, 10)])
        webring.fetch_feeds(self.generators)
 ```
 
 Look at how much time it takes to run the tests.

2022-02-27 14:18 UTC, mlcdf commented
pre-commit.ci autofix

2023-01-27 13:34 UTC, davidag requested changes
@mlcdf Excuse me for taking me so long to review your PR. It's a great improvement to the plugin 👏🏼 🙏🏼 

If you can rebase to main, I think this can be merged as is. The existing tests are already covering the changes and the code is quite straightforward.

2023-01-27 13:55 UTC, justinmayer commented
@davidag: I just enabled a setting for this repository that adds an "Update branch" button, which should allow you to update the PR's feature branch with the commits from `main` without having to request that PR authors do so themselves.

There is a drop-down menu next to that button that allows you to choose the update method: merge commit or rebase. In this case, it seems the rebase option isn't available "due to conflicts", which is strange since right next to this it says "This branch has no conflicts with the base branch", so… 🤷 

Anyway, I hope this extra repo functionality and information is useful, however you choose to utilize it. 😁

2023-01-27 14:10 UTC, mlcdf commented
Hello @davidag! No worries.

I just rebased the branch.

2023-01-27 15:55 UTC, davidag commented
> @davidag: I just enabled a setting for this repository that adds an "Update branch" button, which should allow you to update the PR's feature branch with the commits from `main` without having to request that PR authors do so themselves.

Perfect! Thank you Justin! I think the issue was that the PR was created against `master` but now `main` is the main branch.

@mlcdf Thanks Maxime, I'll take this opportunity to make a new release of the plugin 🚀

2023-01-27 16:06 UTC, merged